#include "word_bank.h"

const char* const WORD_BANK[] = {
"apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew", "kiwi", "lemon",
"orange", "pear", "plum", "quince", "raspberry", "strawberry", "tangerine", "ugli", "vanilla",
"watermelon", "car", "bus", "train", "plane", "bike", "boat", "subway", "tram", "scooter",
"skateboard", "red", "blue", "green", "yellow", "orange", "purple", "pink", "brown", "black",
"white", "run", "jump", "walk", "swim", "climb", "fly", "crawl", "hop", "skip", "jog",
"dog", "cat", "mouse", "rabbit", "bird", "fish", "horse", "cow", "sheep", "goat",
"chicken", "duck", "turkey", "goose", "sparrow", "eagle", "hawk", "owl", "parrot", "pigeon",
"house", "apartment", "building", "barn", "cabin", "castle", "shed", "shack", "mansion", "villa",
"tree", "bush", "flower", "grass", "vine", "shrub", "weed", "leaf", "branch", "root",
"cloud", "sun", "moon", "star", "planet", "comet", "galaxy", "universe", "asteroid", "meteor",
"pen", "pencil", "marker", "crayon", "chalk", "paint", "brush", "canvas", "easel", "notebook",
"book", "magazine", "newspaper", "journal", "dictionary", "encyclopedia", "pamphlet", "brochure", "catalog", "flyer",
"table", "chair", "desk", "bed", "couch", "sofa", "stool", "bench", "cabinet", "shelf",
"bottle", "cup", "glass", "mug", "jug", "flask", "pitcher", "jar", "tin", "can",
"plate", "bowl", "dish", "tray", "pot", "pan", "skillet", "kettle", "saucepan", "grill",
"knife", "fork", "spoon", "ladle", "spatula", "whisk", "tongs", "peeler", "grater", "cutter",
"computer", "laptop", "tablet", "phone", "camera", "printer", "scanner", "monitor", "keyboard", "mouse",
"screen", "display", "projector", "headphones", "speaker", "microphone", "webcam", "router", "modem", "server",
"sunrise", "sunset", "morning", "noon", "afternoon", "evening", "night", "midnight", "dawn", "dusk",
"spring", "summer", "fall", "autumn", "winter", "season", "weather", "temperature", "climate", "forecast",
"wind", "rain", "snow", "hail", "sleet", "storm", "thunder", "lightning", "breeze", "gale",
"ocean", "sea", "lake", "river", "pond", "stream", "creek", "waterfall", "bay", "gulf",
"mountain", "hill", "valley", "plain", "plateau", "ridge", "canyon", "cliff", "peak", "summit",
"forest", "jungle", "woods", "grove", "meadow", "field", "desert", "swamp", "marsh", "wetland",
"rock", "stone", "boulder", "pebble", "sand", "gravel", "soil", "dirt", "mud", "clay",
"metal", "iron", "steel", "copper", "silver", "gold", "platinum", "bronze", "brass", "tin",
"wood", "log", "branch", "twig", "bark", "leaf", "root", "flower", "bud", "seed",
"meat", "beef", "pork", "chicken", "turkey", "lamb", "fish", "shrimp", "crab", "lobster",
"bread", "toast", "bun", "roll", "bagel", "croissant", "muffin", "cookie", "cake", "pie",
"pasta", "noodle", "spaghetti", "macaroni", "lasagna", "ravioli", "dumpling", "wonton", "gnocchi", "ramen",
"rice", "grain", "wheat", "barley", "corn", "oat", "millet", "quinoa", "amaranth", "sorghum",
"fruit", "apple", "banana", "berry", "cherry", "date", "fig", "grape", "kiwi", "lemon",
"vegetable", "carrot", "celery", "broccoli", "cauliflower", "spinach", "lettuce", "cabbage", "kale", "pepper",
"onion", "garlic", "ginger", "spice", "herb", "oregano", "basil", "thyme", "rosemary", "parsley",
"animal", "mammal", "bird", "reptile", "amphibian", "insect", "fish", "whale", "shark", "dolphin",
"bear", "tiger", "lion", "elephant", "giraffe", "monkey", "ape", "gorilla", "chimpanzee", "zebra",
"fox", "wolf", "deer", "rabbit", "squirrel", "chipmunk", "rat", "mouse", "hamster", "guinea",
"engine", "motor", "generator", "turbine", "pump", "compressor", "boiler", "reactor", "conveyor", "crane",
"hammer", "saw", "drill", "wrench", "screwdriver", "pliers", "chisel", "file", "clamp", "vise",
"rope", "chain", "cord", "wire", "cable", "string", "twine", "thread", "yarn", "fabric",
"cloth", "silk", "cotton", "wool", "polyester", "nylon", "linen", "rayon", "velvet", "lace",
"hat", "cap", "helmet", "visor", "beret", "turban", "veil", "mask", "goggles", "glasses",
"shirt", "blouse", "t-shirt", "sweater", "jacket", "coat", "vest", "dress", "skirt", "pants",
"jeans", "trousers", "shorts", "underwear", "socks", "stockings", "shoes", "boots", "sandals", "slippers",
"glove", "mitten", "scarf", "belt", "tie", "bowtie", "button", "zipper", "pocket", "strap",
"watch", "clock", "alarm", "timer", "calendar", "schedule", "agenda", "appointment", "reminder", "note",
"key", "lock", "handle", "knob", "latch", "hinge", "bolt", "screw", "nail", "pin",
"paper", "sheet", "page", "card", "envelope", "letter", "postcard", "stamp", "label", "sticker",
"paint", "ink", "dye", "color", "pigment", "stain", "varnish", "lacquer", "polish", "finish",
"carpet", "rug", "mat", "curtain", "blind", "shade", "towel", "blanket", "pillow", "quilt",
"chair", "sofa", "couch", "table", "desk", "cabinet", "dresser", "wardrobe", "bed", "bunk",
"door", "window", "wall", "ceiling", "floor", "roof", "chimney", "stairs", "elevator", "balcony",
"bathroom", "kitchen", "bedroom", "living", "room", "garage", "garden", "yard", "patio", "porch",
"street", "road", "avenue", "boulevard", "lane", "drive", "highway", "freeway", "bridge", "tunnel",
"city", "town", "village", "suburb", "neighborhood", "district", "borough", "county", "state", "region",
"country", "nation", "empire", "kingdom", "republic", "province", "territory", "colony", "island", "peninsula",
"continent", "world", "earth", "planet", "moon", "sun", "star", "galaxy", "universe", "space",
"computer", "tablet", "phone", "laptop", "printer", "monitor", "keyboard", "mouse", "speaker", "camera",
"television", "radio", "projector", "microphone", "headphone", "earphone", "router", "modem", "console", "remote",
"software", "program", "app", "application", "game", "tool", "editor", "viewer", "browser", "server",
"website", "internet", "network", "cloud", "database", "file", "folder", "document", "spreadsheet", "presentation",
"code", "script", "algorithm", "function", "method", "class", "object", "variable", "constant", "array",
"list", "dictionary", "map", "set", "queue", "stack", "tree", "graph", "node", "edge",
"person", "man", "woman", "child", "adult", "teenager", "baby", "toddler", "elder", "senior",
"friend", "family", "neighbor", "coworker", "teammate", "boss", "employee", "employer", "colleague", "partner",
"student", "teacher", "professor", "lecturer", "coach", "trainer", "instructor", "guide", "mentor", "advisor",
"doctor", "nurse", "dentist", "pharmacist", "surgeon", "therapist", "counselor", "psychologist", "psychiatrist", "consultant",
"lawyer", "attorney", "judge", "police", "officer", "firefighter", "paramedic", "engineer", "scientist", "researcher",
"architect", "designer", "artist", "musician", "writer", "author", "poet", "novelist", "playwright", "director",
"actor", "actress", "singer", "dancer", "comedian", "magician", "performer", "athlete", "player", "coach",
"the", "and", "is", "in", "it", "to", "of", "that", "with", "because",
"for", "as", "on", "at", "by", "from", "this", "we", "you", "they",
"he", "she", "them", "their", "his", "her", "our", "its", "there", "be",
"been", "being", "are", "was", "were", "am", "will", "would", "could", "should",
"do", "does", "doing", "done", "have", "has", "having", "had", "get", "got",
"getting", "go", "going", "went", "gone", "make", "making", "made", "see", "seeing",
"saw", "seen", "know", "knowing", "knew", "known", "think", "thinking", "thought", "say",
"saying", "said", "give", "giving", "gave", "given", "take", "taking", "took", "taken",
"find", "finding", "found", "use", "using", "used", "want", "wanting", "wanted", "like",
"liking", "liked", "love", "loving", "loved", "play", "playing", "played", "work", "working",
"worked", "go", "went", "gone", "goes", "try", "trying", "tried", "start", "starting",
"started", "finish", "finishing", "finished", "run", "running", "ran", "walk", "walking",
"walked", "talk", "talking", "talked", "listen", "listening", "listened", "speak", "speaking", "spoke",
"spoken", "read", "reading", "wrote", "writing", "written", "watch", "watching", "watched", "hear",
"hearing", "heard", "look", "looking", "looked", "live", "living", "lived", "stay", "staying",
"stayed", "stop", "stopping", "stopped", "start", "starting", "started", "begin", "beginning", "began",
"begun", "bring", "bringing", "brought", "build", "building", "built", "learn", "learning", "learned",
"create", "creating", "created", "change", "changing", "changed", "open", "opening", "opened", "close",
"closing", "closed", "move", "moving", "moved", "buy", "buying", "bought", "sell", "selling",
"sold", "help", "helping", "helped", "show", "showing", "showed", "shown", "turn", "turning",
"turned", "ask", "asking", "asked", "answer", "answering", "answered", "explain", "explaining", "explained",
"choose", "choosing", "chose", "chosen", "tell", "telling", "told", "feel", "feeling", "felt",
"bring", "bringing", "brought", "think", "thinking", "thought", "understand", "understanding", "understood", "mean",
"meaning", "meant", "seem", "seeming", "seemed", "let", "letting", "lets", "allow", "allowing",
"allowed", "believe", "believing", "believed", "remember", "remembering", "remembered", "forget", "forgetting", "forgot",
"forgotten", "hope", "hoping", "hoped", "decide", "deciding", "decided", "include", "including", "included",
"become", "becoming", "became", "give", "giving", "gave", "offered", "join", "joining", "joined",
"return", "returning", "returned", "lead", "leading", "led", "grow", "growing", "grew", "grown",
"build", "building", "built", "drive", "driving", "drove", "driven", "reach", "reaching", "reached",
"meet", "meeting", "met", "expect", "expecting", "expected", "receive", "receiving", "received", "improve",
"improving", "improved", "increase", "increasing", "increased", "remain", "remaining", "remained", "explain", "explaining",
"explained", "accept", "accepting", "accepted", "avoid", "avoiding", "avoided", "enjoy", "enjoying", "enjoyed",
"describe", "describing", "described", "send", "sending", "sent", "spend", "spending", "spent", "choose",
"choosing", "chose", "chosen", "begin", "beginning", "began", "begun", "develop", "developing", "developed",
"support", "supporting", "supported", "control", "controlling", "controlled", "manage", "managing", "managed", "use",
"using", "used", "leave", "leaving", "left", "agree", "agreeing", "agreed", "apply", "applying",
"applied", "plan", "planning", "planned", "report", "reporting", "reported", "decide", "deciding", "decided",
"win", "winning", "won", "offer", "offering", "offered", "remember", "remembering", "remembered", "require",
"requiring", "required", "suggest", "suggesting", "suggested", "value", "valuing", "valued", "provide", "providing",
"provided", "understand", "understanding", "understood", "relate", "relating", "related", "control", "controlling", "controlled",
"visit", "visiting", "visited", "travel", "traveling", "traveled", "organize", "organizing", "organized", "hope",
"hoping", "hoped", "fail", "failing", "failed", "check", "checking", "checked", "count", "counting",
"counted", "serve", "serving", "served", "affect", "affecting", "affected", "achieve", "achieving", "achieved",
"design", "designing", "designed", "claim", "claiming", "claimed", "cause", "causing", "caused", "remove",
"removing", "removed", "contain", "containing", "contained", "support", "supporting", "supported", "develop", "developing",
"developed", "require", "requiring", "required", "explain", "explaining", "explained", "arrive", "arriving", "arrived",
"choose", "choosing", "chose", "chosen", "include", "including", "included", "provide", "providing", "provided",
"create", "creating", "created", "consider", "considering", "considered", "protect", "protecting", "protected", "accept",
"accepting", "accepted", "improve", "improving", "improved", "receive", "receiving", "received", "appear", "appearing",
"appeared", "represent", "representing", "represented", "exist", "existing", "existed", "remain", "remaining", "remained",
"listen", "listening", "listened", "recognize", "recognizing", "recognized", "prepare", "preparing", "prepared", "identify",
"identifying", "identified", "establish", "establishing", "established", "determine", "determining", "determined", "define", "defining",
"defined", "prefer", "preferring", "preferred", "answer", "answering", "answered", "contain", "containing", "contained",
"include", "including", "included", "result", "resulting", "resulted", "occur", "occurring", "occurred", "learn",
"learning", "learned", "suggest", "suggesting", "suggested", "recognize", "recognizing", "recognized", "describe", "describing",
"described", "believe", "believing", "believed", "remember", "remembering", "remembered", "realize", "realizing", "realized",
"through", "during", "while", "until", "since", "before", "after", "above", "below", "between",
"around", "about", "across", "toward", "along", "behind", "beside", "under", "near", "next",
"besides", "against", "within", "without", "inside", "outside", "onto", "upon", "among", "upon",
"underneath", "beyond", "amid", "amongst", "concerning", "regarding", "despite", "in", "out", "into",
"against", "facing", "across", "beneath", "besides", "without", "across", "behind", "towards", "throughout",
"because", "although", "however", "therefore", "consequently", "moreover", "furthermore", "besides", "otherwise", "meanwhile",
"thus", "nevertheless", "whereas", "hence", "accordingly", "nonetheless", "nonetheless", "alternatively", "instead", "likewise",
"similarly", "still", "so", "yet", "despite", "nonetheless", "although", "either", "neither", "nor",
"but", "so", "unless", "where", "wherever", "whenever", "whereas", "because", "wherever", "whenever",
"someone", "anyone", "everyone", "nobody", "somebody", "everybody", "anybody", "nobody", "something", "everything",
"anything", "nothing", "myself", "yourself", "himself", "herself", "itself", "ourselves", "themselves", "each",
"both", "several", "some", "many", "much", "few", "fewer", "more", "most", "least",
"another", "other", "any", "some", "every", "either", "neither", "one", "two", "three",
"hundred", "thousand", "million", "billion", "trillion", "next", "previous", "following", "former", "latter",
"first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth", "tenth",
"such", "several", "various", "certain", "different", "similar", "related", "unrelated", "like", "unlike",
"same", "other", "another", "current", "past", "future", "recent", "upcoming", "previous", "latest",
"modern", "old", "ancient", "former", "new", "young", "oldest", "youngest", "earlier", "later",
"long", "short", "tall", "tiny", "small", "big", "large", "huge", "vast", "immense",
"massive", "minuscule", "slight", "light", "heavy", "thin", "thick", "narrow", "wide", "broad",
"deep", "shallow", "empty", "full", "whole", "partial", "half", "complete", "incomplete", "partial",
"entire", "broken", "fixed", "damaged", "destroyed", "restored", "ruined", "renewed", "lost", "found",
"visible", "invisible", "seen", "unseen", "appeared", "disappeared", "vanished", "materialized", "manifested", "occurred",
"reoccurred", "reappeared", "moved", "stayed", "left", "arrived", "departed", "entered", "exited", "opened",
"closed", "shut", "locked", "unlocked", "sealed", "unsealed", "wrapped", "unwrapped", "covered", "uncovered",
"exposed", "hidden", "revealed", "concealed", "disclosed", "informed", "uninformed", "educated", "trained", "untrained",
"practiced", "unpracticed", "skilled", "unskilled", "expert", "novice", "professional", "amateur", "proficient", "inept",
"capable", "incapable", "able", "unable", "qualified", "disqualified", "prepared", "unprepared", "ready", "unready",
"fit", "unfit", "healthy", "unhealthy", "well", "unwell", "sick", "ill", "strong", "weak",
"powerful", "powerless", "mighty", "frail", "sturdy", "fragile", "resilient", "brittle", "solid", "liquid",
"gas", "plasma", "metal", "wood", "stone", "clay", "glass", "plastic", "rubber", "fiber",
"fabric", "cotton", "wool", "silk", "linen", "denim", "leather", "paper", "cardboard", "aluminum",
"steel", "copper", "brass", "bronze", "iron", "gold", "silver", "platinum", "nickel", "zinc",
"titanium", "carbon", "hydrogen", "oxygen", "nitrogen", "helium", "chlorine", "sulfur", "phosphorus", "magnesium",
"calcium", "potassium", "sodium", "lithium", "barium", "boron", "arsenic", "fluorine", "iodine", "bromine",
"uranium", "radium", "plutonium", "neptunium", "thorium", "beryllium", "silicon", "germanium", "tin", "lead",
"mercury", "radon", "neon", "argon", "krypton", "xenon", "tungsten", "cobalt", "manganese", "chromium",
"cadmium", "tellurium", "antimony", "cerium", "lanthanum", "samarium", "ytterbium", "yttrium", "scandium", "thorium",
"actinium", "polonium", "astatine", "francium", "hafnium", "rhenium", "osmium", "iridium", "ruthenium", "palladium",
"bismuth", "thorium", "technetium", "promethium", "dysprosium", "holmium", "erbium", "thulium", "lutetium", "praseodymium",
"neodymium", "samarium", "europium", "gadolinium", "terbium", "copper", "nickel", "palladium", "platinum", "iridium",
"osmium", "ruthenium", "rhodium", "cobalt", "titanium", "vanadium", "chromium", "manganese", "molybdenum", "tantalum",
"niobium", "zirconium", "hafnium", "rhenium", "cerium", "gallium", "indium", "thallium", "lead", "bismuth",
"thorium", "uranium", "neptunium", "plutonium", "americium", "curium", "berkelium", "californium", "einsteinium", "fermium",
"mendelevium", "nobelium", "lawrencium", "rutherfordium", "dubnium", "seaborgium", "bohrium", "hassium", "meitnerium", "darmstadtium",
"roentgenium", "copernicium", "nihonium", "flerovium", "moscovium", "livermorium", "tennessine", "oganesson", "science", "physics",
"chemistry", "biology", "mathematics", "geography", "geology", "astronomy", "astrophysics", "zoology", "botany", "microbiology",
"genetics", "immunology", "neuroscience", "psychology", "sociology", "anthropology", "archaeology", "economics", "politics", "philosophy",
"history", "literature", "poetry", "art", "music", "theater", "film", "painting", "sculpture", "photography",
"architecture", "engineering", "computing", "informatics", "programming", "networking", "hardware", "software", "robotics", "cybernetics"
"John", "Mary", "James", "Linda", "Michael", "Jennifer", "David", "Susan", "Robert", "Karen",
"William", "Lisa", "Christopher", "Patricia", "Daniel", "Jessica", "Thomas", "Sarah", "Matthew", "Nancy",
"Andrew", "Betty", "Paul", "Margaret", "Mark", "Sandra", "Donald", "Ashley", "Steven", "Kimberly",
"George", "Donna", "Joshua", "Emily", "Kevin", "Michelle", "Brian", "Carol", "Edward", "Amanda",
"Ronald", "Melissa", "Jason", "Stephanie", "Jeffrey", "Rebecca", "Ryan", "Laura", "Jacob", "Sharon",
"Gary", "Cynthia", "Nicholas", "Kathleen", "Eric", "Amy", "Jonathan", "Deborah", "Stephen", "Anna",
"Justin", "Ruth", "Brandon", "Shirley", "Samuel", "Brenda", "Frank", "Pamela", "Gregory", "Nicole",
"Alexander", "Katherine", "Raymond", "Samantha", "Patrick", "Christine", "Jack", "Debra", "Dennis", "Rachel",
"Jerry", "Carolyn", "Tyler", "Janet", "Aaron", "Maria", "Henry", "Heather", "Douglas", "Diane",
"Peter", "Virginia", "Adam", "Julie", "Jose", "Joyce", "Nathan", "Victoria", "Zachary", "Olivia",
"Charles", "Barack", "Elon", "Oprah", "Ariana", "Kanye", "Bill", "Jeff", "Taylor", "Rihanna",
"Facebook", "Twitter", "Instagram", "Snapchat", "YouTube", "Reddit", "LinkedIn", "TikTok", "Pinterest", "WhatsApp",
"Google", "Amazon", "eBay", "Walmart", "Target", "BestBuy", "Netflix", "Spotify", "Apple", "Microsoft",
"Samsung", "Sony", "PlayStation", "Xbox", "Nintendo", "Adobe", "Zoom", "Slack", "GitHub", "WordPress",
"McDonald's", "Starbucks", "Subway", "Burger King", "KFC", "Wendy's", "Chick-fil-A", "Taco Bell", "Pizza Hut", "Dunkin'",
"Domino's", "Popeyes", "Chipotle", "Panera", "Panda Express", "IHOP", "Denny's", "Olive Garden", "Applebee's", "Red Lobster",
"Chili's", "Outback", "Cheesecake Factory", "Buffalo Wild Wings", "Five Guys", "Sonic", "Arby's", "P.F. Chang's", "Hardee's", "Carl's Jr.",
"Levi's", "Nike", "Adidas", "Gucci", "Prada", "Louis Vuitton", "H&M", "Zara", "Uniqlo", "Under Armour",
"Marvel", "DC", "Star Wars", "Harry Potter", "Lord of the Rings", "Game of Thrones", "The Simpsons", "SpongeBob", "Batman", "Superman",
"Spider-Man", "Iron Man", "Captain America", "Wonder Woman", "Hulk", "Thor", "Black Panther", "Doctor Strange", "Deadpool", "Joker",
"Barbie", "LEGO", "Hot Wheels", "NERF", "Transformers", "G.I. Joe", "My Little Pony", "Funko Pop", "Monopoly", "Rubik's Cube",
"Fisher-Price", "Play-Doh", "Slinky", "Beyblade", "Polly Pocket", "Tamagotchi", "Yo-Yo", "RC Car", "Action Figure", "Dollhouse",
"iPhone", "iPad", "MacBook", "Surface", "ThinkPad", "Galaxy", "Pixel", "Raspberry Pi", "Arduino", "Kindle",
"Tesla", "Ford", "Chevrolet", "Toyota", "Honda", "BMW", "Audi", "Mercedes", "Lexus", "Nissan",
"Volkswagen", "Hyundai", "Kia", "Subaru", "Mazda", "Jeep", "Dodge", "Chrysler", "Jaguar", "Land Rover",
"Canada", "United States", "Mexico", "Brazil", "Argentina", "Colombia", "Chile", "Peru", "Venezuela", "Bolivia",
"France", "Germany", "Italy", "Spain", "Portugal", "United Kingdom", "Ireland", "Netherlands", "Belgium", "Switzerland",
"Russia", "China", "Japan", "South Korea", "India", "Pakistan", "Bangladesh", "Sri Lanka", "Nepal", "Bhutan",
"Australia", "New Zealand", "Fiji", "Papua New Guinea", "Indonesia", "Malaysia", "Thailand", "Vietnam", "Philippines", "Singapore",
"Egypt", "South Africa", "Nigeria", "Ghana", "Kenya", "Morocco", "Algeria", "Tunisia", "Libya", "Sudan",
"Saudi Arabia", "United Arab Emirates", "Qatar", "Jordan", "Israel", "Turkey", "Iran", "Iraq", "Syria", "Lebanon",
"New York", "Los Angeles", "Chicago", "Houston", "Miami", "London", "Paris", "Rome", "Berlin", "Tokyo",
"Beijing", "Shanghai", "Moscow", "Dubai", "Hong Kong", "Sydney", "Melbourne", "Buenos Aires", "Rio de Janeiro", "Sao Paulo",
"Cairo", "Istanbul", "Mexico City", "Toronto", "Vancouver", "Montreal", "San Francisco", "Seattle", "Boston", "Washington",
"Las Vegas", "Orlando", "Atlanta", "Phoenix", "Philadelphia", "Dallas", "San Diego", "Denver", "Detroit", "Minneapolis",
"Dublin", "Edinburgh", "Barcelona", "Amsterdam", "Brussels", "Vienna", "Prague", "Warsaw", "Budapest", "Athens"
};

const unsigned int WORD_COUNT = sizeof(WORD_BANK) / sizeof(WORD_BANK[0]);